theme = "ayu_dark_ev_trans"

[editor]
line-number = "relative"
true-color = true
auto-pairs = true
idle-timeout = 100

[editor.statusline]
right = ["diagnostics", "position", "file-encoding","version-control", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
insert = "bar"

[keys.normal]
A-up = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-down = ["extend_to_line_bounds", "delete_selection", "paste_after"]

[editor.soft-wrap]
enable = true
max-wrap = 90
max-indent-retain = 40
wrap-indicator = ""  # set wrap-indicator to "" to hide it